<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>dev.lonsing.eclipse.plugins</groupId>
    <artifactId>dev.lonsing.eclipse.plugins.gotoproject.parent</artifactId>
    <version>2.0.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>dev.lonsing.eclipse.plugins.gotoproject.target-platform</artifactId>
  <version>2.0.1-SNAPSHOT</version>
  <packaging>eclipse-target-definition</packaging>

  <name>Go to Project - Eclipse 2026-06 Target Platform</name>

  <build>
    <plugins>
      <plugin>
        <groupId>org.eclipse.tycho.extras</groupId>
        <artifactId>target-platform-validation-plugin</artifactId>
        <version>${tycho.version}</version>
        <executions>
          <execution>
            <id>validate-target-platform</id>
            <goals>
              <goal>validate-target-platform</goal>
            </goals>
            <configuration>
              <checkDependencies>true</checkDependencies>
              <checkProvisioning>true</checkProvisioning>
              <executionEnvironment>JavaSE-21</executionEnvironment>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
