Bundle-Vendor = Philip Lonsing
Bundle-Name = Go to Project
Bundle-Description = Quickly select a workspace project in Project Explorer or Package Explorer.
command_category_name = Go to Project
command_goToProject_name = Project...
